import book.BookManager;
import book.Book;
import java.io.IOException;
import javax.swing.*;
import student.StudentManager;

public class StudentAndBookManagementFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentAndBookManagementFrame.class.getName());

    /**
     * Creates new form StudentAndBookManagementFrame
     */
    public StudentAndBookManagementFrame() {
        initComponents();
        try {
            BookManager.loadBooks();
            updateBookPanelTitle();
            if(BookManager.booksArr.size() != 0) {
                setDisplayBookInfo(0);
            }
        } catch (IOException e) {
        }
        try {
            StudentManager.loadStudents();
        } catch (IOException e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSearchBy = new javax.swing.ButtonGroup();
        lblPageTitle = new javax.swing.JLabel();
        pnlStudentInfo = new javax.swing.JPanel();
        btnStudentPrevious = new javax.swing.JButton();
        btnStudentNext = new javax.swing.JButton();
        btnStudentFirst = new javax.swing.JButton();
        btnStudentLast = new javax.swing.JButton();
        btnCreateStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        pnlBookInfo = new javax.swing.JPanel();
        lblBookTitle = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        lblBookAuthor = new javax.swing.JLabel();
        txtBookAuthor = new javax.swing.JTextField();
        lblBookISBN = new javax.swing.JLabel();
        txtBookISBN = new javax.swing.JTextField();
        lblBookPrice = new javax.swing.JLabel();
        txtBookPrice = new javax.swing.JTextField();
        txtBookCategory = new javax.swing.JTextField();
        lblBookCategory = new javax.swing.JLabel();
        lblBookAvailable = new javax.swing.JLabel();
        txtBookAvailable = new javax.swing.JTextField();
        btnBookPrevious = new javax.swing.JButton();
        btnBookNext = new javax.swing.JButton();
        btnBookLast = new javax.swing.JButton();
        btnAddNewBook = new javax.swing.JButton();
        btnEditBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        btnBookFirst = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        rdBtnSearchByStudent = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        rdBtnSearchByStudent2 = new javax.swing.JRadioButton();
        lblSearchResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSearchResult = new javax.swing.JTextArea();
        btnDisplayStudentInfo = new javax.swing.JButton();
        btnDisplayBookInfo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student and Book Management");

        lblPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPageTitle.setForeground(new java.awt.Color(21, 58, 255));
        lblPageTitle.setText("Student and Book Management");

        pnlStudentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Student 0 of 0"));

        btnStudentPrevious.setBackground(new java.awt.Color(153, 153, 153));
        btnStudentPrevious.setForeground(new java.awt.Color(51, 51, 51));
        btnStudentPrevious.setText("Previous");
        btnStudentPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentPreviousActionPerformed(evt);
            }
        });

        btnStudentNext.setBackground(new java.awt.Color(153, 153, 153));
        btnStudentNext.setForeground(new java.awt.Color(51, 51, 51));
        btnStudentNext.setText("Next");
        btnStudentNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentNextActionPerformed(evt);
            }
        });

        btnStudentFirst.setBackground(new java.awt.Color(153, 153, 153));
        btnStudentFirst.setForeground(new java.awt.Color(51, 51, 51));
        btnStudentFirst.setText("First");
        btnStudentFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentFirstActionPerformed(evt);
            }
        });

        btnStudentLast.setBackground(new java.awt.Color(153, 153, 153));
        btnStudentLast.setForeground(new java.awt.Color(51, 51, 51));
        btnStudentLast.setText("Last");
        btnStudentLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentLastActionPerformed(evt);
            }
        });

        btnCreateStudent.setBackground(new java.awt.Color(102, 255, 102));
        btnCreateStudent.setForeground(new java.awt.Color(0, 0, 0));
        btnCreateStudent.setText("Create");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setBackground(new java.awt.Color(0, 204, 255));
        btnEditStudent.setForeground(new java.awt.Color(0, 0, 0));
        btnEditStudent.setText("Edit");
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        lblStudentName.setText("👤  Name: ");

        txtStudentName.setEditable(false);
        txtStudentName.setFocusable(false);

        lblStudentId.setText("🆔  Student ID: ");

        txtStudentId.setEditable(false);
        txtStudentId.setFocusable(false);

        javax.swing.GroupLayout pnlStudentInfoLayout = new javax.swing.GroupLayout(pnlStudentInfo);
        pnlStudentInfo.setLayout(pnlStudentInfoLayout);
        pnlStudentInfoLayout.setHorizontalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addComponent(btnStudentPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStudentLast)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStudentId)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateStudent)
                            .addComponent(btnDeleteStudent, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditStudent, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnStudentFirst, btnStudentLast, btnStudentNext, btnStudentPrevious});

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateStudent, btnDeleteStudent, btnEditStudent});

        pnlStudentInfoLayout.setVerticalGroup(
            pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentInfoLayout.createSequentialGroup()
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCreateStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteStudent))
                    .addGroup(pnlStudentInfoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentName)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentId)
                            .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlStudentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentPrevious)
                    .addComponent(btnStudentNext)
                    .addComponent(btnStudentFirst)
                    .addComponent(btnStudentLast))
                .addContainerGap())
        );

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnStudentFirst, btnStudentLast, btnStudentNext, btnStudentPrevious});

        pnlStudentInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateStudent, btnDeleteStudent, btnEditStudent});

        pnlBookInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Book 0 of 0"));

        lblBookTitle.setText("📕  Title: ");

        txtBookTitle.setEditable(false);
        txtBookTitle.setFocusable(false);

        lblBookAuthor.setText("👤  Author: ");

        txtBookAuthor.setEditable(false);
        txtBookAuthor.setFocusable(false);

        lblBookISBN.setText("🆔  ISBN: ");

        txtBookISBN.setEditable(false);
        txtBookISBN.setFocusable(false);

        lblBookPrice.setText("💲  Price: ");

        txtBookPrice.setEditable(false);
        txtBookPrice.setFocusable(false);

        txtBookCategory.setEditable(false);
        txtBookCategory.setFocusable(false);

        lblBookCategory.setText("📚  Category: ");

        lblBookAvailable.setText("✔️ Available: ");

        txtBookAvailable.setEditable(false);
        txtBookAvailable.setFocusable(false);

        btnBookPrevious.setBackground(new java.awt.Color(153, 153, 153));
        btnBookPrevious.setForeground(new java.awt.Color(51, 51, 51));
        btnBookPrevious.setText("Previous");
        btnBookPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookPreviousActionPerformed(evt);
            }
        });

        btnBookNext.setBackground(new java.awt.Color(153, 153, 153));
        btnBookNext.setForeground(new java.awt.Color(51, 51, 51));
        btnBookNext.setText("Next");
        btnBookNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNextActionPerformed(evt);
            }
        });

        btnBookLast.setBackground(new java.awt.Color(153, 153, 153));
        btnBookLast.setForeground(new java.awt.Color(51, 51, 51));
        btnBookLast.setText("Last");
        btnBookLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookLastActionPerformed(evt);
            }
        });

        btnAddNewBook.setBackground(new java.awt.Color(102, 255, 102));
        btnAddNewBook.setForeground(new java.awt.Color(0, 0, 0));
        btnAddNewBook.setText("Add New Book");
        btnAddNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewBookActionPerformed(evt);
            }
        });

        btnEditBook.setBackground(new java.awt.Color(0, 204, 255));
        btnEditBook.setForeground(new java.awt.Color(0, 0, 0));
        btnEditBook.setText("Edit Book");
        btnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteBook.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteBook.setText("Delete Book");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        btnBookFirst.setBackground(new java.awt.Color(153, 153, 153));
        btnBookFirst.setForeground(new java.awt.Color(51, 51, 51));
        btnBookFirst.setText("First");
        btnBookFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFirstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookInfoLayout = new javax.swing.GroupLayout(pnlBookInfo);
        pnlBookInfo.setLayout(pnlBookInfoLayout);
        pnlBookInfoLayout.setHorizontalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addComponent(btnBookPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBookLast))
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblBookISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBookAuthor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(lblBookTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtBookAuthor)
                                    .addComponent(txtBookISBN)))
                            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblBookAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBookCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBookPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBookPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtBookCategory)
                                    .addComponent(txtBookAvailable))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteBook)))))
        );

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBookFirst, btnBookLast, btnBookNext, btnBookPrevious});

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteBook, btnEditBook});

        pnlBookInfoLayout.setVerticalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addComponent(btnAddNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteBook))
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookTitle)
                            .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookAuthor)
                            .addComponent(txtBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookISBN)
                            .addComponent(txtBookISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookPrice)
                            .addComponent(txtBookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookCategory)
                            .addComponent(txtBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBookAvailable)
                            .addComponent(txtBookAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookPrevious)
                    .addComponent(btnBookNext)
                    .addComponent(btnBookLast)
                    .addComponent(btnBookFirst))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBookFirst, btnBookLast, btnBookNext, btnBookPrevious});

        pnlBookInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddNewBook, btnDeleteBook, btnEditBook});

        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblSearch.setText("🔎 Search: ");

        btnGrpSearchBy.add(rdBtnSearchByStudent);
        rdBtnSearchByStudent.setText("👤  Student");

        btnSearch.setBackground(new java.awt.Color(255, 255, 0));
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setText("🔎 Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnGrpSearchBy.add(rdBtnSearchByStudent2);
        rdBtnSearchByStudent2.setText("📕  Book");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch)
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSearchLayout.createSequentialGroup()
                                .addComponent(rdBtnSearchByStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdBtnSearchByStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnSearchByStudent)
                    .addComponent(rdBtnSearchByStudent2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblSearchResult.setText("📂 Search Result: ");

        txtAreaSearchResult.setColumns(20);
        txtAreaSearchResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaSearchResult);

        btnDisplayStudentInfo.setBackground(new java.awt.Color(51, 102, 255));
        btnDisplayStudentInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayStudentInfo.setText("👤 Display Student Information");
        btnDisplayStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayStudentInfoActionPerformed(evt);
            }
        });

        btnDisplayBookInfo.setBackground(new java.awt.Color(51, 102, 255));
        btnDisplayBookInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayBookInfo.setText("📕 Display Book Information");
        btnDisplayBookInfo.setToolTipText("");
        btnDisplayBookInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayBookInfoActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("🔚 Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblPageTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlBookInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlStudentInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSearchResult)
                            .addComponent(btnDisplayStudentInfo)
                            .addComponent(btnDisplayBookInfo)
                            .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisplayBookInfo, btnDisplayStudentInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPageTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblSearchResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplayStudentInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplayBookInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDisplayBookInfo, btnDisplayStudentInfo, btnExit});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBookPanelTitle() {
        int bookNumber = currentBookIndex + 1;
        int numOfTotalBooks = BookManager.booksArr.size();
        String newTitle;
        if(numOfTotalBooks != 0) {
            newTitle = String.format("Book %d of %d", bookNumber, numOfTotalBooks);
        } else {
            newTitle = "Book 0 of 0";
        }
        pnlBookInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(newTitle));
    }
    
    private void setDisplayBookInfo(int bookIndex) {
        Book selectedBook = BookManager.booksArr.get(bookIndex);
        
        txtBookTitle.setText(selectedBook.getTitle());
        txtBookAuthor.setText(selectedBook.getAuthor());
        txtBookISBN.setText(selectedBook.getIsbn());
        txtBookPrice.setText(String.valueOf(selectedBook.getPrice()));
        txtBookCategory.setText(selectedBook.getCategory());
        txtBookAvailable.setText(String.valueOf(selectedBook.getAvailable()));
    }
    
    private void clearDisplayBookInfo() {
        txtBookTitle.setText("");
        txtBookAuthor.setText("");
        txtBookISBN.setText("");
        txtBookPrice.setText("");
        txtBookCategory.setText("");
        txtBookAvailable.setText("");
    }
    
    private void btnDisplayStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayStudentInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisplayStudentInfoActionPerformed

    private void btnDisplayBookInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayBookInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisplayBookInfoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            BookManager.saveBooks();
            StudentManager.saveStudents();
            JOptionPane.showMessageDialog(null, "Program terminated.", "Exit", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        } catch (IOException e) {
            showErrorMessage("Failed to save data.\nPlease try again.");
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnStudentPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentPreviousActionPerformed

    private void btnStudentNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentNextActionPerformed

    private void btnStudentFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentFirstActionPerformed

    private void btnStudentLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentLastActionPerformed

    private void btnBookPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookPreviousActionPerformed
        if(currentBookIndex > 0) {
            currentBookIndex--;
            updateBookPanelTitle();
            setDisplayBookInfo(currentBookIndex);
        }
    }//GEN-LAST:event_btnBookPreviousActionPerformed

    private void btnBookNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNextActionPerformed
        int lastBookIndex = BookManager.booksArr.size() - 1;
        if(currentBookIndex != lastBookIndex && lastBookIndex != -1) {
            currentBookIndex++;
            updateBookPanelTitle();
            setDisplayBookInfo(currentBookIndex);
        }
    }//GEN-LAST:event_btnBookNextActionPerformed

    private void btnBookFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFirstActionPerformed
       int booksArrLength = BookManager.booksArr.size();
        if(booksArrLength != 0) {
            currentBookIndex = 0;
            updateBookPanelTitle();
            setDisplayBookInfo(currentBookIndex);
        }
    }//GEN-LAST:event_btnBookFirstActionPerformed

    private void btnBookLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookLastActionPerformed
        int booksArrLength = BookManager.booksArr.size();
        if(booksArrLength != 0) {
            int lastBookIndex = booksArrLength - 1;
            currentBookIndex = lastBookIndex;
            updateBookPanelTitle();
            setDisplayBookInfo(currentBookIndex);
        }
    }//GEN-LAST:event_btnBookLastActionPerformed

    private void btnAddNewBookActionPerformed(java.awt.event.ActionEvent evt) {
        JTextField txtBookTitleInput = new JTextField(15);
        JTextField txtBookAuthorInput = new JTextField(15);
        JTextField txtBookISBNInput = new JTextField(15);
        JTextField txtBookPriceInput = new JTextField(15);
        JTextField txtBookCategoryInput = new JTextField(15);

        JPanel mainPanel = new JPanel();
        JPanel bookTitlePanel = new JPanel();
        JPanel bookAuthorPanel = new JPanel();
        JPanel bookISBNPanel = new JPanel();
        JPanel bookPricePanel = new JPanel();
        JPanel bookCategoryPanel = new JPanel();
        
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        bookTitlePanel.setLayout(new BoxLayout(bookTitlePanel, BoxLayout.X_AXIS));
        bookAuthorPanel.setLayout(new BoxLayout(bookAuthorPanel, BoxLayout.X_AXIS));
        bookISBNPanel.setLayout(new BoxLayout(bookISBNPanel, BoxLayout.X_AXIS));
        bookPricePanel.setLayout(new BoxLayout(bookPricePanel, BoxLayout.X_AXIS));
        bookCategoryPanel.setLayout(new BoxLayout(bookCategoryPanel, BoxLayout.X_AXIS));
        
        bookTitlePanel.add(new JLabel("📘 Title:           "));
        bookAuthorPanel.add(new JLabel("👤 Author:        "));
        bookISBNPanel.add(new JLabel("📃 ISBN:          "));
        bookPricePanel.add(new JLabel("💲 Price:          "));
        bookCategoryPanel.add(new JLabel("📚 Category:    "));
        
        bookTitlePanel.add(txtBookTitleInput);
        bookAuthorPanel.add(txtBookAuthorInput);
        bookISBNPanel.add(txtBookISBNInput);
        bookPricePanel.add(txtBookPriceInput);
        bookCategoryPanel.add(txtBookCategoryInput);
        
        JLabel lblCreateBook = new JLabel("Create Book");
        lblCreateBook.setForeground(new java.awt.Color(0, 102, 0));
        lblCreateBook.setFont(new java.awt.Font("Segoe UI", 1, 13));
        
        mainPanel.add(lblCreateBook);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookTitlePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookAuthorPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookISBNPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookPricePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookCategoryPanel);

        int result = JOptionPane.showConfirmDialog(null, mainPanel, "Add New Book", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION) {
            try {
                String bookTitleInput = txtBookTitleInput.getText();
                String bookAuthorInput = txtBookAuthorInput.getText();
                String bookISBNInput = txtBookISBNInput.getText();
                String bookCategoryInput = txtBookCategoryInput.getText();

                if(bookTitleInput.equals("") || bookAuthorInput.equals("") || bookCategoryInput .equals("") || txtBookPriceInput.getText().equals("") || bookCategoryInput.equals("")) {
                    throw new IllegalArgumentException();
                }
                
                Double bookPriceInput = Double.parseDouble(txtBookPriceInput.getText());
                
                Book newBook = new Book(bookTitleInput, bookAuthorInput, bookISBNInput, bookPriceInput, bookCategoryInput, true);
                BookManager.booksArr.add(newBook);
                updateBookPanelTitle();
                
                JOptionPane.showMessageDialog(null, "New book added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                showErrorMessage("Please enter only numbers and decimals for book price.");
            } catch (IllegalArgumentException e) {
                showErrorMessage("Please enter all the necessary information for creating book.");
            }
        }
    }
    
    private void btnEditBookActionPerformed(java.awt.event.ActionEvent evt) {
        if(BookManager.booksArr.size() == 0) {
            showErrorMessage("No book selected currently.\n Please add a book first.");
            return;
        }
        JTextField txtBookTitleInput = new JTextField(15);
        JTextField txtBookAuthorInput = new JTextField(15);
        JTextField txtBookISBNInput = new JTextField(15);
        JTextField txtBookPriceInput = new JTextField(15);
        JTextField txtBookCategoryInput = new JTextField(15);

        JPanel mainPanel = new JPanel();
        JPanel bookTitlePanel = new JPanel();
        JPanel bookAuthorPanel = new JPanel();
        JPanel bookISBNPanel = new JPanel();
        JPanel bookPricePanel = new JPanel();
        JPanel bookCategoryPanel = new JPanel();
        
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        bookTitlePanel.setLayout(new BoxLayout(bookTitlePanel, BoxLayout.X_AXIS));
        bookAuthorPanel.setLayout(new BoxLayout(bookAuthorPanel, BoxLayout.X_AXIS));
        bookISBNPanel.setLayout(new BoxLayout(bookISBNPanel, BoxLayout.X_AXIS));
        bookPricePanel.setLayout(new BoxLayout(bookPricePanel, BoxLayout.X_AXIS));
        bookCategoryPanel.setLayout(new BoxLayout(bookCategoryPanel, BoxLayout.X_AXIS));
        
        bookTitlePanel.add(new JLabel("📘 Title:           "));
        bookAuthorPanel.add(new JLabel("👤 Author:        "));
        bookISBNPanel.add(new JLabel("📃 ISBN:          "));
        bookPricePanel.add(new JLabel("💲 Price:          "));
        bookCategoryPanel.add(new JLabel("📚 Category:    "));
        
        txtBookTitleInput.setText(txtBookTitle.getText());
        txtBookAuthorInput.setText(txtBookAuthor.getText());
        txtBookISBNInput.setText(txtBookISBN.getText());
        txtBookCategoryInput.setText(txtBookCategory.getText());
        txtBookPriceInput.setText(txtBookPrice.getText());
        
        bookTitlePanel.add(txtBookTitleInput);
        bookAuthorPanel.add(txtBookAuthorInput);
        bookISBNPanel.add(txtBookISBNInput);
        bookPricePanel.add(txtBookPriceInput);
        bookCategoryPanel.add(txtBookCategoryInput);
        
        JLabel lblEditBook = new JLabel("Edit Book");
        lblEditBook.setForeground(new java.awt.Color(0, 102, 255));
        lblEditBook.setFont(new java.awt.Font("Segoe UI", 1, 13));
        
        mainPanel.add(lblEditBook);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookTitlePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookAuthorPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookISBNPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookPricePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookCategoryPanel);

        int result = JOptionPane.showConfirmDialog(null, mainPanel, "Edit Book - " + txtBookISBN.getText(), JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION) {
            try {
                String bookTitleInput = txtBookTitleInput.getText();
                String bookAuthorInput = txtBookAuthorInput.getText();
                String bookISBNInput = txtBookISBNInput.getText();
                String bookCategoryInput = txtBookCategoryInput.getText();

                if(bookTitleInput.equals("") || bookAuthorInput.equals("") || bookCategoryInput .equals("") || txtBookPriceInput.getText().equals("") || bookCategoryInput.equals("")) {
                    throw new IllegalArgumentException();
                }
                
                Double bookPriceInput = Double.parseDouble(txtBookPriceInput.getText());
                
                Book editedBook = new Book(bookTitleInput, bookAuthorInput, bookISBNInput, bookPriceInput, bookCategoryInput, true);
                BookManager.booksArr.set(currentBookIndex, editedBook);
                updateBookPanelTitle();
                setDisplayBookInfo(currentBookIndex);
                
                JOptionPane.showMessageDialog(null, "Book edited successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                showErrorMessage("Please enter only numbers and decimals for book price.");
            } catch (IllegalArgumentException e) {
                showErrorMessage("Please enter all the necessary information for creating book.");
            }
        }
    }
    
    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {
        JTextField txtBookTitleInput = new JTextField(15);
        JTextField txtBookAuthorInput = new JTextField(15);
        JTextField txtBookISBNInput = new JTextField(15);
        JTextField txtBookPriceInput = new JTextField(15);
        JTextField txtBookCategoryInput = new JTextField(15);

        JPanel mainPanel = new JPanel();
        JPanel bookTitlePanel = new JPanel();
        JPanel bookAuthorPanel = new JPanel();
        JPanel bookISBNPanel = new JPanel();
        JPanel bookPricePanel = new JPanel();
        JPanel bookCategoryPanel = new JPanel();
        
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        bookTitlePanel.setLayout(new BoxLayout(bookTitlePanel, BoxLayout.X_AXIS));
        bookAuthorPanel.setLayout(new BoxLayout(bookAuthorPanel, BoxLayout.X_AXIS));
        bookISBNPanel.setLayout(new BoxLayout(bookISBNPanel, BoxLayout.X_AXIS));
        bookPricePanel.setLayout(new BoxLayout(bookPricePanel, BoxLayout.X_AXIS));
        bookCategoryPanel.setLayout(new BoxLayout(bookCategoryPanel, BoxLayout.X_AXIS));
        
        bookTitlePanel.add(new JLabel("📘 Title:           "));
        bookAuthorPanel.add(new JLabel("👤 Author:        "));
        bookISBNPanel.add(new JLabel("📃 ISBN:          "));
        bookPricePanel.add(new JLabel("💲 Price:          "));
        bookCategoryPanel.add(new JLabel("📚 Category:    "));
        
        txtBookTitleInput.setText(txtBookTitle.getText());
        txtBookAuthorInput.setText(txtBookAuthor.getText());
        txtBookISBNInput.setText(txtBookISBN.getText());
        txtBookCategoryInput.setText(txtBookCategory.getText());
        txtBookPriceInput.setText(txtBookPrice.getText());
        
        txtBookTitleInput.setFocusable(false);
        txtBookAuthorInput.setFocusable(false);
        txtBookISBNInput.setFocusable(false);
        txtBookCategoryInput.setFocusable(false);
        txtBookPriceInput.setFocusable(false);
        
        bookTitlePanel.add(txtBookTitleInput);
        bookAuthorPanel.add(txtBookAuthorInput);
        bookISBNPanel.add(txtBookISBNInput);
        bookPricePanel.add(txtBookPriceInput);
        bookCategoryPanel.add(txtBookCategoryInput);
        
        JLabel lblDeleteBook = new JLabel("Delete this book permanently?");
        lblDeleteBook.setForeground(new java.awt.Color(255, 51, 51));
        lblDeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 13));
        
        mainPanel.add(lblDeleteBook);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookTitlePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookAuthorPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookISBNPanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookPricePanel);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(bookCategoryPanel);

        int result = JOptionPane.showConfirmDialog(null, mainPanel, "Delete Book - " + txtBookISBN.getText(), JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION) {
            BookManager.booksArr.remove(currentBookIndex);
            if(BookManager.booksArr.size() != 0) {
                currentBookIndex = 0;
                setDisplayBookInfo(currentBookIndex);
            } else {
                currentBookIndex = -1;
                clearDisplayBookInfo();
            }
            updateBookPanelTitle();

            JOptionPane.showMessageDialog(null, "Book deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void showErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var mainFrame = new StudentAndBookManagementFrame();
                mainFrame.setLocationRelativeTo(null);
                mainFrame.setResizable(false);
                mainFrame.setVisible(true);
            }
        });
    }
    
    // Custom variables
    private int currentBookIndex = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewBook;
    private javax.swing.JButton btnBookFirst;
    private javax.swing.JButton btnBookLast;
    private javax.swing.JButton btnBookNext;
    private javax.swing.JButton btnBookPrevious;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDisplayBookInfo;
    private javax.swing.JButton btnDisplayStudentInfo;
    private javax.swing.JButton btnEditBook;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGrpSearchBy;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnStudentFirst;
    private javax.swing.JButton btnStudentLast;
    private javax.swing.JButton btnStudentNext;
    private javax.swing.JButton btnStudentPrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookAuthor;
    private javax.swing.JLabel lblBookAvailable;
    private javax.swing.JLabel lblBookCategory;
    private javax.swing.JLabel lblBookISBN;
    private javax.swing.JLabel lblBookPrice;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchResult;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel pnlBookInfo;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlStudentInfo;
    private javax.swing.JRadioButton rdBtnSearchByStudent;
    private javax.swing.JRadioButton rdBtnSearchByStudent2;
    private javax.swing.JTextArea txtAreaSearchResult;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookAvailable;
    private javax.swing.JTextField txtBookCategory;
    private javax.swing.JTextField txtBookISBN;
    private javax.swing.JTextField txtBookPrice;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
